services:
  frontend:
    # Build the image from the Dockerfile in the current directory
    build: .
    container_name: iod-frontend
    ports:
      # Map the host port (from an env variable) to the container's port 80
      - "${NGINX_EXTERNAL_PORT}:80"
    environment:
      # These variables will be used by the entrypoint script in Nginx
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    restart: unless-stopped

networks:
  # The frontend can optionally connect to a network to reach the backend
  app-network:
    driver: bridge
