name: Frontend Docker Image CI

on:
  push:
    branches: [ "master" ] # Trigger on our working branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: linux/arm64
        push: true
        # Use a new tag for the frontend image
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/iod-frontend:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/iod-frontend:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/iod-frontend:cache,mode=max